[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.railway"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

[environment]
PORT = "8080"
NODE_ENV = "production"

# Railway服务配置
[[services]]
name = "zerotouch-frontend"
source = "."

[services.build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.railway"
buildContext = "."

[services.deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

[services.variables]
PORT = "8080"
NODE_ENV = "production"
